# Generated by Django 3.2.6 on 2021-08-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Designates whether the user is a manager', verbose_name='manager status'),
        ),
    ]
