# Generated by Django 3.2.6 on 2021-08-29 21:46

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='site_pics')),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'cities',
            },
        ),
        migrations.CreateModel(
            name='DeweyDecimalClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
                ('family_num', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='SocialSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('pages_num', models.IntegerField(blank=True, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('available_copies', models.IntegerField(blank=True, null=True)),
                ('available_borrowing', models.BooleanField()),
                ('available', models.BooleanField()),
                ('image', models.ImageField(default='default.jpg', upload_to='book_pics')),
                ('brief', ckeditor.fields.RichTextField()),
                ('snippet', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='booking.author')),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='booking.deweydecimalclassification')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='booking.publisher')),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='birth_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='booking.city'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handler', models.CharField(max_length=50)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='booking.publisher')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='booking.socialsite')),
            ],
        ),
    ]
