# Generated by Django 3.2.6 on 2021-08-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='deweydecimalclassification',
            name='family',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deweydecimalclassification',
            name='family_num',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='socialsite',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
