# Generated by Django 3.2.6 on 2021-08-18 08:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='brief',
            field=ckeditor.fields.RichTextField(default='snippet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='snippet',
            field=models.TextField(null=True),
        ),
    ]
