# Generated by Django 3.2.6 on 2021-08-18 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20210818_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='snippet',
            field=models.TextField(default='snippet'),
            preserve_default=False,
        ),
    ]
