# Generated by Django 3.2.6 on 2021-08-12 13:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', ckeditor.fields.RichTextField()),
                ('snippet', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='pics')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_modifed', models.DateTimeField(auto_now=True)),
                ('is_pinned', models.BooleanField(default=False, help_text='Designates whether the post is pinned', verbose_name='pinned status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['title'],
            },
        ),
    ]
