# Generated by Django 3.2.6 on 2021-08-09 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
