# Generated by Django 3.2.6 on 2021-08-17 00:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_reply_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address')),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Contact Us',
                'db_table': 'contact_us',
            },
        ),
    ]
