# Generated by Django 3.2.6 on 2021-08-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_pinned',
            field=models.BooleanField(default=False, help_text='Designates whether the post is pinned', verbose_name='pinned status'),
        ),
    ]
