# Generated by Django 3.2.6 on 2021-08-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='telephone',
        ),
        migrations.AddField(
            model_name='contactus',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Designates whether the request is URGENT.', verbose_name='urgent status'),
        ),
        migrations.AddField(
            model_name='contactus',
            name='username',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
