# Generated by Django 3.2.6 on 2021-08-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210817_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(help_text='We will use this email to reach out to you.', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='message',
            field=models.TextField(help_text='Please provide your query here.'),
        ),
    ]
