# Generated by Django 3.2.6 on 2021-08-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210818_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-is_pinned', '-date_posted']},
        ),
    ]
