# Generated by Django 3.2.6 on 2021-08-20 23:10

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20210820_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=20, verbose_name='Type')),
                ('url', models.URLField()),
                ('date_reported', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
