# Generated by Django 3.2.6 on 2021-08-20 23:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=ckeditor.fields.RichTextField(blank=True, help_text='If you want to leave a note for the reviewer'),
        ),
    ]
