# Generated by Django 3.2.6 on 2021-08-24 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0015_comment_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.ManyToManyField(related_name='blog_reply_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
