# Generated by Django 3.2.6 on 2021-08-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210824_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', through='blog.PostCategory', to='blog.Category'),
        ),
    ]
