# Generated by Django 3.2.6 on 2021-08-26 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_reply_likes'),
        ('blog', '0017_alter_post_categories'),
    ]

    operations = [
    ]
